### ISSUE TITLE
Agregar protección a endpoints post, put y delete

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/stac-fastapi#2]
# Descripción
Los endpoints post, put y delete deben requerir autenticación.

En este mismo issue se debe realizar el ajuste en stac-data-tools para que sigan funcionando todos sus comandos

# Consideraciones 
Tomar de referencia la rama [createAuth](https://github.com/PEM-Humboldt/biotablero-search-backend/tree/createAuth) del backend para hacer esta implementación en este repositorio.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/stac-fastapi/2?planning-poker) with Zenhub @cazapatamar @denarch22 @ManuelStardust

**Comment by denarch22** [comment]
Se intento realizar los ajustes para la autenticación en el servidor , sin embargo identifique que los cambios no se estaban realizando, adicional intente realizar pruebas con un endpoint de pruebas que tienen al app pero aunque cambiaba la respuesta no se evidenciaba, según la revisión realizada el día de hoy con ayuda de Erika se identifico que estaba utilizando otra imagen y no la que se había cargado al contenedor, por lo tanto se realizara ese ajuste primero y después se continuara con esta.

**Comment by denarch22** [comment]
Se realizo el ajuste para tomar las variables de autenticación y se agrego las clases de autenticación para generar y validar el token, sin embargo realizando pruebas se encontró que el servidor esta retornando un error 500 antes del 401 por los que se genero una tarea para realizar el ajuste del manejador de errores del servidor.

**Comment by erikasv** [comment]
@denarch22 veo enlazado a la tarea el PR de ajuste sobre stac-data-tools, pero no el de stac-fastapi

**Comment by erikasv** [comment]
@denarch22 también cambiarle el título al PR, algo más explicativo (la rama se puede quedar así, pero importante tener en cuenta que "adjustmentCodeCollection" no me dice nada sobre cambios relacionados con la autenticación
