### ISSUE TITLE
ajustar manejador de errores stac-fastApi

### ISSUE THREAD

**Issue by denarch22** [PEM-Humboldt/stac-fastapi#7]
Durante el ajuste de agregar autenticación a los endpoint de stac-fastApi se identifico que el manejador de errores esta retornando 2 errores cuando se hace una peticion sin token :
<img width="883" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFBJQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7af3645dcbb5a5966cfddefbfd7a251fc7ee5d8b/image.png" alt="image.png" />

pero cuando realizo la consulta en stac-data-tools: aparece el error 500:<img width="1071" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFhJQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d29a63d5fc8f88871f07cfe4dd36097e713cf3df/image.png" alt="image.png" />

Por lo que es necesario realizar el ajuste y realice la verificación del token antes de realizar el proceso que realiza el endpoint.

**Comment by erikasv** [comment]
@denarch22 no entiendo por qué esta tarea la creaste en stac-fastapi, es un ajuste que debería hacerse en stac-data-tools

Además, se deben manejar por separado, el ajuste al manejo de errores y la agregación de la autenticación. Primero la autenticación, luego el manejo de errores
